### ISSUE TITLE
Error with plone.content.dynamic definition

### ISSUE THREAD

**Issue by libargutxi** [collective/collective.volto.subsites#4]
When running Plone instance I have an error with this definition:
[plone.content.dynamic](https://github.com/collective/collective.volto.subsites/blob/main/src/collective/volto/subsites/restapi/services/subsite/configure.zcml#L17)

Am I missing something? where is that ruleset definition?

**Comment by cekk** [comment]
hmmm..probably because i missed p.a.caching import like this: https://github.com/RedTurtle/design.plone.contenttypes/blob/master/src/design/plone/contenttypes/configure.zcml#L16


Can you try it and open a pull-request?

**Comment by erral** [comment]
Plone 5.2 uses plone.app.caching 2.1.x which does not have the plone.content.dynamic ruleset. 

This ruleset was included in plone.app.caching 3.0.0a1, thus we need to include that as a dependency in setup.py.

I will add a PR.
